@startuml Watches_ecommerce
left to right direction
actor Customer
actor Admin

usecase "Browse Watches" as UC_Browse
usecase "Search Watches" as UC_Search
usecase "Add to Cart" as UC_AddCart
usecase "View Cart" as UC_ViewCart
usecase "Checkout" as UC_Checkout
usecase "Place Order" as UC_Order
usecase "Leave Review" as UC_Review
usecase "Manage Products" as UC_ManageProducts
usecase "Manage Orders" as UC_ManageOrders
usecase "Manage Users" as UC_ManageUsers

Customer --> UC_Browse
Customer --> UC_Search
Customer --> UC_AddCart
Customer --> UC_ViewCart
Customer --> UC_Checkout
Customer --> UC_Order
Customer --> UC_Review

Admin --> UC_ManageProducts
Admin --> UC_ManageOrders
Admin --> UC_ManageUsers
@enduml
